version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres-data:
