// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddItem implements addItem operation.
//
// Add a new item.
//
// POST /items
func (UnimplementedHandler) AddItem(ctx context.Context, req *Item) (r *Item, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteItem implements deleteItem operation.
//
// Deletes a item.
//
// DELETE /items/{id}
func (UnimplementedHandler) DeleteItem(ctx context.Context, params DeleteItemParams) error {
	return ht.ErrNotImplemented
}

// GetItem implements getItem operation.
//
// Returns a item.
//
// GET /items/{id}
func (UnimplementedHandler) GetItem(ctx context.Context, params GetItemParams) (r *Item, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateItem implements updateItem operation.
//
// Updates a item.
//
// POST /items/{id}
func (UnimplementedHandler) UpdateItem(ctx context.Context, params UpdateItemParams) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
